"""Deck-length bench: collect run artifacts and write docs/COMPARE.md (docs/PLAN.md, docs/AGENT_COST.md).

    python bench/lengthbench/report.py collect RUNS.json   # copy sources, render sheets, write result.json
    python bench/lengthbench/report.py compare             # write docs/COMPARE.md from result.json files

RUNS.json: {"t1": {"slidemark": {"dir": "...", "run": {...}}, "python-pptx": {...}}, ...}, where "run" is
the row from bench/agent_cost.py analyze() plus "wall_s" (first to last transcript timestamp) and "accepted".
Sources are copied exactly as the agents wrote them; .pptx files are not kept.
"""

from __future__ import annotations

import json
import shutil
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
ARMS = {"slidemark": "deck.md", "python-pptx": "build.py"}
LENGTHS = {"t1": 5, "t2": 15, "t3": 25}
KEEP = ("calls", "output", "thinking", "cost", "cost_above_start", "images", "builds", "wall_s", "accepted")


def _tokens(text: str) -> int:
    import tiktoken

    return len(tiktoken.get_encoding("o200k_base").encode(text))


def collect(runs_path: str) -> None:
    sys.path.insert(0, str(ROOT / "src"))
    from slidemark.preview import contact_sheet, pptx_to_pngs

    runs = json.loads(Path(runs_path).read_text(encoding="utf-8"))
    for bid, arms in runs.items():
        result: dict = {"brief": bid, "slides": LENGTHS[bid]}
        for arm, info in arms.items():
            src_dir = Path(info["dir"])
            dest = HERE / bid / arm
            dest.mkdir(parents=True, exist_ok=True)
            src = src_dir / ARMS[arm]
            shutil.copyfile(src, dest / ARMS[arm])
            with tempfile.TemporaryDirectory() as tmp:
                pngs = pptx_to_pngs(src_dir / "deck.pptx", tmp)
                contact_sheet(pngs, dest / "sheet.png")
            row = {k: info["run"].get(k) for k in KEEP}
            row["source_tokens"] = _tokens(src.read_text(encoding="utf-8"))
            result[arm] = row
        (HERE / bid / "result.json").write_text(json.dumps(result, ensure_ascii=False, indent=1) + "\n")
        print("collected", bid)


def _pct(a: float, b: float) -> str:
    return f"{100 * a / b:.0f}%" if b else "–"


def compare() -> None:
    rows = []
    for bid in LENGTHS:
        p = HERE / bid / "result.json"
        if p.exists():
            rows.append(json.loads(p.read_text(encoding="utf-8")))
    out = [
        "# SlideMark vs python-pptx: one topic at 5, 15 and 25 slides",
        "",
        "Generated by `bench/lengthbench/report.py` from `bench/lengthbench/<brief>/result.json`;",
        "do not edit by hand.",
        "",
        "Both arms got the same brief (a fictional FY2027 business plan in dense Japanese business style;",
        "the longer briefs extend the shorter one) and the same model (Sonnet, fresh subagent,",
        "one run per arm). The SlideMark arm could read only SKILL.md; the python-pptx arm had",
        "python-pptx only. Both could render previews.",
        "",
        "- **Calls:** model API requests from brief to hand-back.",
        "- **Time:** wall clock from the request to the agent's final reply (render and build included).",
        "- **Cost:** units above the shared first call: fresh input + 1.25 x cache write + 0.1 x cache read"
        " + 5 x output (docs/AGENT_COST.md).",
        "- **Source:** o200k tokens of the file the agent wrote (`deck.md` or `build.py`).",
        "",
        "| Slides | Arm | Calls | Time | Output tokens | Cost | Source tokens | Images viewed | Accepted |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        for arm in ARMS:
            a = r.get(arm)
            if not a:
                continue
            out.append(
                f"| {r['slides']} | {arm} | {a['calls']} | {a['wall_s']:.0f} s | {a['output']:,} |"
                f" {a['cost_above_start']:,} | {a['source_tokens']:,} | {a['images']} |"
                f" {'yes' if a['accepted'] else 'no'} |"
            )
    out += ["", "**SlideMark as a share of python-pptx**", ""]
    out.append("| Slides | Calls | Time | Output | Cost | Source |")
    out.append("|---|---|---|---|---|---|")
    for r in rows:
        s, p = r.get("slidemark"), r.get("python-pptx")
        if s and p:
            out.append(
                f"| {r['slides']} | {s['calls']} / {p['calls']} | {_pct(s['wall_s'], p['wall_s'])} |"
                f" {_pct(s['output'], p['output'])} | {_pct(s['cost_above_start'], p['cost_above_start'])} |"
                f" {_pct(s['source_tokens'], p['source_tokens'])} |"
            )
    for r in rows:
        bid = r["brief"]
        out += ["", f"## {r['slides']} slides (`bench/lengthbench/{bid}/`)", ""]
        for arm, fname in ARMS.items():
            if arm not in r:
                continue
            src = (HERE / bid / arm / fname).read_text(encoding="utf-8")
            lang = "markdown" if fname.endswith(".md") else "python"
            out += [
                f"**{arm}**: `{fname}`, {r[arm]['source_tokens']:,} tokens, {src.count(chr(10)) + 1} lines",
                "",
                f"![{arm} {r['slides']} slides](../bench/lengthbench/{bid}/{arm}/sheet.png)",
                "",
                f"<details><summary>{fname}</summary>",
                "",
                f"````{lang}",
                src.rstrip(),
                "````",
                "",
                "</details>",
                "",
            ]
    (ROOT / "docs" / "COMPARE.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("wrote docs/COMPARE.md")


if __name__ == "__main__":
    if sys.argv[1:2] == ["collect"]:
        collect(sys.argv[2])
    else:
        compare()
