"""Text metrics from committed advance-width tables: line counts and heights without PowerPoint.

Latin text is measured with the table of the style font family (Calibri, Arial, Yu Gothic/Meiryo, mono;
data in ``metrics/widths.json`` generated by ``scripts/gen_metrics.py``
from Carlito, Liberation Sans, IPAPGothic and
Liberation Mono), so results do not depend on installed fonts. Unknown families use Arial. Ideographs and
full-width kana count as 1em. Word wrap for Latin, per-character wrap with simple kinsoku rules for CJK.
The renderer imports the shared constants so that both sides agree.
"""

from __future__ import annotations

import json
import unicodedata
from functools import cache
from pathlib import Path

from ..ir import Paragraph, Style
from ..units import EMU_PER_PT

LINE_LATIN = 1.2  # line height / font size
LINE_CJK = 1.3
PARA_GAP = 0.25  # space before every paragraph but the first, x font size
SAFETY = 1.03  # estimate inflation
CELL_PAD_X = 91440  # 0.1in, table cell margins (renderer applies the same)
CELL_PAD_Y = 45720  # 0.05in

# Kinsoku shori. No line may start with a NO_START char (closing punctuation, small kana, long vowel mark)
# or end with a NO_END char (opening bracket). Violations are fixed by pushing the previous character down
# to the next line (oikomi-free "oidashi"), which is the conservative choice: it never needs fewer lines than
# the real renderer. The renderer writes ``eaLnBrk="1" hangingPunct="0"`` so PowerPoint behaves the same.
NO_START = set(
    "、。，．・：；！？）］｝〕〉》」』】ー゛゜ゝゞぁぃぅぇぉっゃゅょゎァィゥェォッャュョヮヵヶ々〻‼⁇⁈⁉"
    "､｡｣ﾞﾟ,.!?:;)]}%"
)
NO_END = set("（［｛〔〈《「『【｢([{")


_METRICS = Path(__file__).parent / "metrics" / "widths.json"
_DEFAULT_EM = 0.6  # a char missing from every table
_default_font = "arial"


def font_key(name: str | None) -> str:
    """Metrics table for a font family name; unknown families fall back to Arial."""
    n = (name or "").lower()
    if not n:
        return _default_font
    if "calibri" in n or "carlito" in n:
        return "calibri"
    if any(k in n for k in ("gothic", "meiryo", "ipa", "mincho", "noto sans cjk", "hiragino", "游")):
        return "jp"
    if any(k in n for k in ("consolas", "mono", "courier", "menlo")):
        return "mono"
    return "arial"


def set_default_font(name: str | None) -> None:
    """Font family used when a call gives none (the layout sets the theme's body font per slide)."""
    global _default_font
    _default_font = "arial"  # font_key returns the current default for an empty name: reset first
    _default_font = font_key(name)


@cache
def _tables() -> dict[str, dict[str, dict[int, int]]]:
    raw = json.loads(_METRICS.read_text(encoding="utf-8"))
    out: dict[str, dict[str, dict[int, int]]] = {}
    for font, kinds in raw.items():
        out[font] = {}
        for kind, runs in kinds.items():
            t: dict[int, int] = {}
            for start, widths in runs.items():
                base = int(start, 16)
                for i, w in enumerate(widths):
                    t[base + i] = w
            out[font][kind] = t
    return out


def is_cjk(ch: str) -> bool:
    return unicodedata.east_asian_width(ch) in ("W", "F")


def has_cjk(text: str) -> bool:
    return any(is_cjk(c) for c in text)


@cache
def _char_em(ch: str, kind: str, font: str) -> float:
    if is_cjk(ch):
        return 1.0
    if unicodedata.east_asian_width(ch) == "H":
        return 0.5
    if unicodedata.combining(ch) or ch in "\u200b\u200c\u200d\ufeff":
        return 0.0
    tabs = _tables()
    if kind == "mono":
        font, kind = "mono", "regular"
    for f in (font, "arial"):
        kinds = tabs.get(f, {})
        w = kinds.get(kind, kinds.get("regular", {})).get(ord(ch))
        if w is not None:
            return w / 1000
    return _DEFAULT_EM


def char_em(ch: str, kind: str = "regular", font: str | None = None) -> float:
    """Advance width of one character in em units (kind: regular, bold, mono; font: family name or None)."""
    return _char_em(ch, kind, font_key(font))


def text_em(text: str, bold: bool = False, mono: bool = False, font: str | None = None) -> float:
    kind = "mono" if mono else ("bold" if bold else "regular")
    key = font_key(font)
    return sum(_char_em(c, kind, key) for c in text)


def list_indent(size_pt: float, level: int) -> tuple[int, int]:
    """(marL, indent) in EMU for a list paragraph; indent is negative (hanging bullet)."""
    hang = round(size_pt * 1.3 * EMU_PER_PT)
    return hang * (level + 1), -hang


def _units(
    segments: list[tuple[str, bool, bool]], font: str | None = None
) -> list[tuple[float, float, str, bool, str]]:
    """Split styled text into wrap units: (width_em, trailing_space_em, first_char, hard_break, last_char)."""
    units: list[tuple[float, float, str, bool, str]] = []
    key = font_key(font)
    st = {"word": "", "w": 0.0, "sp": 0.0}

    def flush():
        if st["word"] or st["sp"]:
            units.append((st["w"], st["sp"], st["word"][:1], False, st["word"][-1:]))
        st["word"], st["w"], st["sp"] = "", 0.0, 0.0

    for text, bold, mono in segments:
        kind = "mono" if mono else ("bold" if bold else "regular")
        for ch in text:
            if ch in "\n\v":
                flush()
                units.append((0.0, 0.0, "", True, ""))
            elif ch in " \t":
                st["sp"] += _char_em(" ", kind, key)
            elif is_cjk(ch) or ch in NO_START or ch in NO_END:
                if is_cjk(ch):
                    flush()
                    units.append((_char_em(ch, kind, key), 0.0, ch, False, ch))
                else:  # ASCII/half-width punctuation stays glued to its word
                    if st["sp"]:
                        flush()
                    st["word"] += ch
                    st["w"] += _char_em(ch, kind, key)
            else:
                if st["sp"]:
                    flush()
                st["word"] += ch
                st["w"] += _char_em(ch, kind, key)
    flush()
    return units


def count_lines(
    segments: list[tuple[str, bool, bool]], width_pt: float, size_pt: float, font: str | None = None
) -> int:
    """Number of lines the styled text needs in ``width_pt`` at ``size_pt`` (with kinsoku)."""
    width = max(width_pt / max(size_pt, 1.0), 1.0)  # in em
    lines, cur = 1, 0.0
    line: list[tuple[float, float, str, bool, str]] = []  # units on the current line
    for u in _units(segments, font):
        w, sp, first, hard, _last = u
        if hard:
            lines += 1
            cur = 0.0
            line = []
            continue
        if cur > 0 and cur + w > width + 1e-6:
            # wrap before ``u``; kinsoku may drag trailing CJK units of this line down with it
            carry: list[tuple[float, float, str, bool, str]] = []
            starts_bad = first in NO_START and is_cjk(first)
            while len(line) > 1 and (starts_bad or (line[-1][4] in NO_END and is_cjk(line[-1][4]))):
                prev = line.pop()
                carry.insert(0, prev)
                starts_bad = prev[2] in NO_START and is_cjk(prev[2])
            lines += 1
            line = carry
            cur = sum(c[0] + c[1] for c in carry)
        if w > width:  # long word: breaks anywhere
            n = int(-(-w // width))
            lines += n - 1
            cur = w - (n - 1) * width
            line = [u]
        else:
            cur += w
            line.append(u)
        cur += sp
    return lines


def para_segments(p: Paragraph, bold: bool = False, mono: bool = False) -> list[tuple[str, bool, bool]]:
    return [(r.text, bold or r.bold, mono or r.code) for r in p.runs]


def paragraphs_height(
    paragraphs: list[Paragraph],
    width_emu: float,
    style: Style,
    scale: float = 1.0,
    *,
    default_size: float = 18,
    mono: bool = False,
) -> float:
    """Estimated height in EMU of ``paragraphs`` wrapped into ``width_emu`` (insets already removed)."""
    base = style.font_size or default_size
    font = style.font
    total_pt = 0.0
    for i, p in enumerate(paragraphs):
        size = (p.style.font_size if p.style and p.style.font_size else base) * scale
        indent = list_indent(size, p.level)[0] if p.marker else 0
        wpt = (width_emu - indent) / EMU_PER_PT
        bold = bool((p.style and p.style.bold) or style.bold)
        lines = count_lines(para_segments(p, bold, mono), wpt, size, font)
        ls = (p.style.line_spacing if p.style and p.style.line_spacing else style.line_spacing) or 1.0
        lh = size * (LINE_CJK if has_cjk(p.plain) else LINE_LATIN) * ls
        total_pt += lines * lh + (size * PARA_GAP if i > 0 else 0)
    return total_pt * EMU_PER_PT * SAFETY


def code_height(text: str, width_emu: float, size_pt: float) -> float:
    """Height in EMU of a code block body (monospace, wrapped at the box width)."""
    cols = max(int(width_emu / EMU_PER_PT / (size_pt * 0.6)), 1)
    lines = 0
    for line in text.expandtabs(4).split("\n"):
        lines += max(1, -(-len(line) // cols))
    return lines * size_pt * LINE_LATIN * EMU_PER_PT * SAFETY


def effective_scale(base_size: float, scale: float, min_font: float) -> float:
    """Autofit factor for an element: never shrink below ``min_font`` pt, never grow."""
    if scale >= 1.0 or base_size <= min_font:
        return 1.0
    return min(1.0, max(scale, min_font / base_size))
