"""Text metrics from committed advance-width tables: line counts and heights without PowerPoint.

Latin text is measured with the table of the style font family (Calibri, Arial, Yu Gothic/Meiryo, mono;
data in ``metrics/widths.json`` generated by ``scripts/gen_metrics.py``
from Carlito, Liberation Sans, IPAPGothic and
Liberation Mono), so results do not depend on installed fonts. Unknown families use Arial widened by 13%
(19% bold). Ideographs and
full-width kana count as 1em. Word wrap for Latin, per-character wrap with simple kinsoku rules for CJK.
The renderer imports the shared constants so that both sides agree.
"""

from __future__ import annotations

import json
import re
import unicodedata
from functools import cache
from pathlib import Path

from ..ir import Paragraph, Style
from ..theme import LayoutTokens
from ..units import EMU_PER_PT, to_emu

SAFETY = 1.03  # estimate inflation

# The look constants live in ``theme.layout`` (LayoutTokens). Layout, lint, critique and the renderer all
# call ``set_tokens(theme.layout)`` before measuring, so both sides agree. The aliases below are the schema
# defaults, kept for code and tests that want "the usual value".
_tok = LayoutTokens()
LINE_LATIN = _tok.line_latin
LINE_CJK = _tok.line_cjk
PARA_GAP = _tok.para_gap
CELL_PAD_X = to_emu(_tok.cell_pad_x)
CELL_PAD_Y = to_emu(_tok.cell_pad_y)


def set_tokens(tokens: LayoutTokens) -> None:
    """Line heights, paragraph gap and cell paddings used by every measure in this process."""
    global _tok
    _tok = tokens


def tokens() -> LayoutTokens:
    return _tok


def para_gap() -> float:
    return _tok.para_gap


def cell_pad() -> tuple[int, int]:
    """(x, y) table cell margins in EMU."""
    try:
        return to_emu(_tok.cell_pad_x), to_emu(_tok.cell_pad_y)
    except ValueError:
        return CELL_PAD_X, CELL_PAD_Y


# Kinsoku shori. No line may start with a NO_START char (closing punctuation, small kana, long vowel mark)
# or end with a NO_END char (opening bracket). Violations are fixed by pushing the previous character down
# to the next line (oikomi-free "oidashi"), which is the conservative choice: it never needs fewer lines than
# the real renderer. The renderer writes ``eaLnBrk="1" hangingPunct="0"`` so PowerPoint behaves the same.
NO_START = set(
    "、。，．・：；！？）］｝〕〉》」』】ー゛゜ゝゞぁぃぅぇぉっゃゅょゎァィゥェォッャュョヮヵヶ々〻‼⁇⁈⁉"
    "､｡｣ﾞﾟ,.!?:;)]}%"
)
NO_END = set("（［｛〔〈《「『【｢([{")


# DejaVu Sans is 1.13x Arial (bold 1.19x); viewers substitute it for families without a table
UNKNOWN_FONT_WIDEN = 1.13
_METRICS = Path(__file__).parent / "metrics" / "widths.json"
_DEFAULT_EM = 0.6  # a char missing from every table
_default_font = "arial"


def font_key(name: str | None) -> str:
    """Metrics table for a font family name; unknown families are Arial inflated by ``UNKNOWN_FONT_WIDEN``."""
    n = (name or "").lower()
    if not n:
        return _default_font
    if "calibri" in n or "carlito" in n:
        return "calibri"
    if any(k in n for k in ("gothic", "meiryo", "ipa", "mincho", "noto sans cjk", "hiragino", "游")):
        return "jp"
    if any(k in n for k in ("consolas", "mono", "courier", "menlo")):
        return "mono"
    if any(k in n for k in ("arial", "helvetica", "liberation sans", "arimo")):
        return "arial"
    return "wide"  # unknown family: the viewer may substitute a wider font (DejaVu, Verdana, Inter)


def set_default_font(name: str | None) -> None:
    """Font family used when a call gives none (the layout sets the theme's body font per slide)."""
    global _default_font
    _default_font = "arial"  # font_key returns the current default for an empty name: reset first
    _default_font = font_key(name)


@cache
def _tables() -> dict[str, dict[str, dict[int, int]]]:
    raw = json.loads(_METRICS.read_text(encoding="utf-8"))
    out: dict[str, dict[str, dict[int, int]]] = {}
    for font, kinds in raw.items():
        out[font] = {}
        for kind, runs in kinds.items():
            t: dict[int, int] = {}
            for start, widths in runs.items():
                base = int(start, 16)
                for i, w in enumerate(widths):
                    t[base + i] = w
            out[font][kind] = t
    return out


NBSP = "\u00a0"
BIND_MAX = 12  # orphan control: both of the last two words must be at most this many characters


def _bindable(w: str) -> bool:
    return (
        0 < len(w) <= BIND_MAX
        and not has_cjk(w)
        and NBSP not in w
        and "://" not in w
        and "www." not in w
        and "@" not in w
    )


@cache
def _bind_cached(texts: tuple[str, ...], skip: tuple[bool, ...]) -> tuple[str, ...]:
    full = "".join(texts)
    cut = max(full.rfind("\n"), full.rfind("\v"), full.rfind("\r")) + 1  # only the last line can orphan
    tail = full[cut:]
    end = len(tail.rstrip(" \t"))
    words = tail[:end].split(" ")
    if sum(1 for w in words if w) < 3 or "\t" in tail[:end]:
        return texts
    w2 = words[-1]
    w1 = words[-2]  # an empty w1 means a double space: leave it alone
    if not (_bindable(w1) and _bindable(w2)):
        return texts
    gap = cut + end - len(w2) - 1  # index of the single space between the last two words
    first = gap - len(w1)
    stop = gap + 1 + len(w2)
    out, pos, hit = [], 0, False
    for t, sk in zip(texts, skip, strict=True):
        a, b = pos, pos + len(t)
        pos = b
        if sk and a < stop and b > first:
            return texts  # the words sit in a code run or a badge: never touch it
        if a <= gap < b:
            t = t[: gap - a] + NBSP + t[gap - a + 1 :]
            hit = True
        out.append(t)
    return tuple(out) if hit else texts


WJ = "\u2060"  # WORD JOINER: invisible, zero width, forbids a break on both sides
CJK_UNITS = "万億兆千百円件人名社店台歳年月日時分秒割倍回点個本枚品位階期週目部課号番級"  # counters
_SIGN_NUM = re.compile(r"([▲△▼+−±¥$￥])(?=\d)")
_NUM_PCT = re.compile(r"(?<=\d)(?=[％])")


def _unit_re(units: str) -> re.Pattern:
    u = f"[{re.escape(units)}]"
    return re.compile(rf"(\d(?:[\d,.]*\d)?[％%]?)({u})({u})?")


_UNIT_RE = _unit_re(CJK_UNITS)


def join_cjk_units(text: str, units: str | None = None) -> str:
    """Keep Japanese numbers with their units (``38万円``, ``▲8%``, ``54歳``) on one line.

    Viewers break between any two CJK characters and between a digit and a CJK character, so U+2060
    goes after a sign that precedes a digit and between a number and up to two unit characters.
    The caller decides whether the text is CJK-relevant and skips code runs, links and badges."""
    if not any(c.isdigit() for c in text):
        return text
    rx = _UNIT_RE if units is None else _unit_re(units)
    text = _SIGN_NUM.sub(lambda m: m.group(1) + WJ, text)
    text = _NUM_PCT.sub(WJ, text)
    return rx.sub(lambda m: WJ.join(g for g in m.groups() if g), text)


def bound_texts(runs) -> list[str]:
    """Run texts of a paragraph with its last two short words joined by a no-break space (orphan control).

    A paragraph that ends in a lone word wraps ugly ("... 2027–2029" alone on a line). When the paragraph
    has at least three words and both of the last two are at most ``BIND_MAX`` characters, the space
    between them becomes U+00A0. Never for CJK words, URLs, code runs or badges; text that already has a
    no-break space there is left as is. Layout (``para_segments``) and renderer both call this, so line
    counts agree; the importer turns U+00A0 back into a space.
    """
    texts = tuple(r.text for r in runs)
    skip = tuple(
        bool(getattr(r, "code", False) or getattr(r, "highlight", None) or getattr(r, "link", None))
        for r in runs
    )
    if " " in "".join(texts):
        texts = _bind_cached(texts, skip)
    return list(_join_cached(texts, skip, _tok.cjk_unit_join)) if _tok.cjk_unit_join else list(texts)


@cache
def _join_cached(texts: tuple[str, ...], skip: tuple[bool, ...], on: bool) -> tuple[str, ...]:
    if not on or not has_cjk("".join(texts)):
        return texts
    return tuple(t if sk or "://" in t else join_cjk_units(t) for t, sk in zip(texts, skip, strict=True))


def bind_last_words(text: str) -> str:
    """:func:`bound_texts` for one plain string."""
    return _bind_cached((text,), (False,))[0]


def is_cjk(ch: str) -> bool:
    if ch < "\u1100":  # nothing below the Hangul Jamo block is wide or full-width
        return False
    return unicodedata.east_asian_width(ch) in ("W", "F")


def is_katakana(ch: str) -> bool:
    """Full-width katakana letters and the long vowel mark (not the middle dot, which is a break point)."""
    return "\u30a1" <= ch <= "\u30fa" or ch in "\u30fc\u30fd\u30fe" or "\u31f0" <= ch <= "\u31ff"


def has_cjk(text: str) -> bool:
    return any(is_cjk(c) for c in text)


@cache
def _base_em(ch: str, kind: str, font: str) -> float:
    if is_cjk(ch):
        return 1.0
    if unicodedata.east_asian_width(ch) == "H":
        return 0.5
    if unicodedata.combining(ch) or ch in "\u200b\u200c\u200d\u2060\ufeff":
        return 0.0
    if ch == NBSP:
        ch = " "
    if font == "wide":
        return _base_em(ch, kind, "arial") * (UNKNOWN_FONT_WIDEN + (0.06 if kind == "bold" else 0.0))
    tabs = _tables()
    if kind == "mono":
        font, kind = "mono", "regular"
    for f in (font, "arial"):
        kinds = tabs.get(f, {})
        w = kinds.get(kind, kinds.get("regular", {})).get(ord(ch))
        if w is not None:
            return w / 1000
    return _DEFAULT_EM


_char_em = _base_em


def char_em(ch: str, kind: str = "regular", font: str | None = None) -> float:
    """Advance width of one character in em units (kind: regular, bold, mono; font: family name or None)."""
    return _base_em(ch, kind, font_key(font))


def text_em(text: str, bold: bool = False, mono: bool = False, font: str | None = None) -> float:
    kind = "mono" if mono else ("bold" if bold else "regular")
    key = font_key(font)
    return sum(_char_em(c, kind, key) for c in text)


def list_indent(size_pt: float, level: int) -> tuple[int, int]:
    """(marL, indent) in EMU for a list paragraph; indent is negative (hanging bullet)."""
    hang = round(size_pt * 1.3 * EMU_PER_PT)
    return hang * (level + 1), -hang


Segment = tuple[str, bool, bool] | tuple[str, bool, bool, bool]  # (text, bold, mono[, badge])


_UNITS_CACHE: dict = {}


def _units(
    segments: list[Segment], font: str | None = None, extra: float = 0.0
) -> list[tuple[float, float, str, bool, str]]:
    """Memoised ``_units0``: the same text is measured at many widths and sizes (units are width-free)."""
    tk = tokens()
    key = (tuple(segments), font, extra, _default_font, tk.badge_pad, tk.badge_pad_cjk)
    hit = _UNITS_CACHE.get(key)
    if hit is None:
        if len(_UNITS_CACHE) > 100_000:
            _UNITS_CACHE.clear()
        hit = _UNITS_CACHE[key] = _units0(segments, font, extra)
    return hit


def _glue_prev(u: tuple[float, float, str, bool, str]) -> bool:
    return not u[3] and u[1] == 0.0 and len(u[2]) == 1 and u[2] == u[4] and is_cjk(u[2])


def _units0(
    segments: list[Segment], font: str | None = None, extra: float = 0.0
) -> list[tuple[float, float, str, bool, str]]:
    """Split styled text into wrap units: (width_em, trailing_space_em, first_char, hard_break, last_char).

    A badge segment (4th item true) is one unbreakable unit: its text plus the full-width padding the
    renderer adds around CJK badge text. ``extra`` is the letter spacing (em) added after every character.
    """
    units: list[tuple[float, float, str, bool, str]] = []
    key = font_key(font)

    def _char_em(ch: str, kind: str, key: str) -> float:  # noqa: F811 - adds the letter spacing
        return _base_em(ch, kind, key) + extra

    st = {"word": "", "w": 0.0, "sp": 0.0}

    def flush():
        if st["word"] or st["sp"]:
            units.append((st["w"], st["sp"], st["word"][:1], False, st["word"][-1:]))
        st["word"], st["w"], st["sp"] = "", 0.0, 0.0

    for seg in segments:
        text, bold, mono = seg[0], seg[1], seg[2]
        kind = "mono" if mono else ("bold" if bold else "regular")
        if len(seg) > 3 and seg[3] and text.strip() and "\n" not in text and "\v" not in text:
            flush()
            tk = tokens()  # the padding the renderer adds on both sides (full-width or no-break spaces)
            pad = tk.badge_pad_cjk * 1.0 if has_cjk(text) else tk.badge_pad * _char_em(" ", kind, key)
            w = sum(_char_em(c, kind, key) for c in text) + 2 * pad
            units.append((w, 0.0, "", False, ""))
            continue
        for ch in text:
            if st["word"].endswith(WJ) and ch not in " \t\n\v":  # glued to the previous character
                st["word"] += ch
                st["w"] += _char_em(ch, kind, key)
            elif ch == WJ and not st["word"] and not st["sp"] and units and _glue_prev(units[-1]):
                w0, _, f0, _, _ = units.pop()  # a CJK character before the joiner joins its word
                st["word"], st["w"] = f0 + ch, w0
            elif ch in "\n\v":
                flush()
                units.append((0.0, 0.0, "", True, ""))
            elif ch in " \t":
                st["sp"] += _char_em(" ", kind, key)
            elif is_katakana(ch):  # a katakana run is one word: never cut inside it unless it is too long
                if st["sp"] or (st["word"] and not is_katakana(st["word"][-1])):
                    flush()
                st["word"] += ch
                st["w"] += _char_em(ch, kind, key)
            elif is_cjk(ch) or ch in NO_START or ch in NO_END:
                if is_cjk(ch):
                    flush()
                    units.append((_char_em(ch, kind, key), 0.0, ch, False, ch))
                else:  # ASCII/half-width punctuation stays glued to its word
                    if st["sp"]:
                        flush()
                    st["word"] += ch
                    st["w"] += _char_em(ch, kind, key)
            else:
                if st["sp"] or (st["word"] and is_katakana(st["word"][-1])):
                    flush()
                st["word"] += ch
                st["w"] += _char_em(ch, kind, key)
    flush()
    return units


_LINES_CACHE: dict = {}


def count_lines(
    segments: list[Segment], width_pt: float, size_pt: float, font: str | None = None, spacing_pt: float = 0.0
) -> int:
    """Number of lines the styled text needs in ``width_pt`` at ``size_pt`` (with kinsoku).

    ``spacing_pt`` is the CSS letter spacing added after every character. Results are memoised
    per (segments, width, size, font, spacing): layout re-measures the same text in many trials."""
    return _lines_tail(segments, width_pt, size_pt, font, spacing_pt)[0]


def _lines_tail(
    segments: list[Segment], width_pt: float, size_pt: float, font: str | None, spacing_pt: float
) -> tuple[int, float]:
    """(lines, width in em of the last line), memoised."""
    key = (tuple(segments), width_pt, size_pt, font, spacing_pt, _default_font)
    hit = _LINES_CACHE.get(key)
    if hit is None:
        if len(_LINES_CACHE) > 200_000:
            _LINES_CACHE.clear()
        hit = _LINES_CACHE[key] = _count_lines(segments, width_pt, size_pt, font, spacing_pt)
    return hit


def _count_lines(
    segments: list[Segment], width_pt: float, size_pt: float, font: str | None, spacing_pt: float
) -> tuple[int, float]:
    width = max(width_pt / max(size_pt, 1.0), 1.0)  # in em
    lines, cur = 1, 0.0
    line: list[tuple[float, float, str, bool, str]] = []  # units on the current line
    for u in _units(segments, font, spacing_pt / max(size_pt, 1.0)):
        w, sp, first, hard, _last = u
        if hard:
            lines += 1
            cur = 0.0
            line = []
            continue
        if cur > 0 and cur + w > width + 1e-6:
            # wrap before ``u``; kinsoku may drag trailing CJK units of this line down with it
            carry: list[tuple[float, float, str, bool, str]] = []
            starts_bad = first in NO_START and is_cjk(first)
            while len(line) > 1 and (starts_bad or (line[-1][4] in NO_END and is_cjk(line[-1][4]))):
                prev = line.pop()
                carry.insert(0, prev)
                starts_bad = prev[2] in NO_START and is_cjk(prev[2])
            lines += 1
            line = carry
            cur = sum(c[0] + c[1] for c in carry)
        if w > width:  # long word: breaks anywhere
            n = int(-(-w // width))
            lines += n - 1
            cur = w - (n - 1) * width
            line = [u]
        else:
            cur += w
            line.append(u)
        cur += sp
    return lines, cur


def para_segments(
    p: Paragraph, bold: bool = False, mono: bool = False, transform: str | None = None
) -> list[Segment]:
    """Styled segments of a paragraph; ``transform`` (CSS text-transform) is applied as the renderer does."""
    from .css import transform_text

    return [
        (
            transform_text(t, transform),
            bold or r.bold or bool(r.highlight),
            mono or r.code,
            bool(r.highlight),
        )
        for r, t in zip(p.runs, bound_texts(p.runs), strict=True)
    ]


def text_spacing(style: Style, p: Paragraph | None = None) -> tuple[float, str | None]:
    """(letter spacing pt, text transform) of a paragraph: its own style over the element style."""
    ps = p.style if p is not None else None
    ls = ps.letter_spacing if ps and ps.letter_spacing is not None else style.letter_spacing
    tf = ps.text_transform if ps and ps.text_transform else style.text_transform
    return ls or 0.0, tf


_SQUEEZE_CACHE: dict = {}


def _explicit_spacing(style: Style, p: Paragraph | None) -> bool:
    ps = p.style if p is not None else None
    return bool((ps and ps.letter_spacing) or style.letter_spacing)


def paragraph_squeeze(
    p: Paragraph,
    style: Style,
    width_pt: float,
    size_pt: float,
    segments: list[Segment] | None = None,
    *,
    mono: bool = False,
) -> float:
    """Letter spacing (pt, <= 0, rounded to 0.01) that pulls a CJK orphan back onto the previous line.

    A paragraph with CJK text whose last line is at most ``cjk_orphan_chars`` characters wide gets the
    smallest spacing (steps of 0.01 em, up to ``cjk_squeeze_max`` em) at which it needs one line less, also
    when the line width is ``cjk_squeeze_margin`` narrower (renders wrap earlier than the model). 0.0 when
    nothing helps, the token is off, or the deck set a letter spacing itself (explicit spacing wins).
    The renderer applies it per paragraph (``fill_text``); ``paragraphs_height(squeeze=True)`` counts it."""
    tk = _tok
    if tk.cjk_squeeze_max <= 0 or tk.cjk_orphan_chars <= 0 or mono or _explicit_spacing(style, p):
        return 0.0
    if not p.runs or not has_cjk(p.plain):
        return 0.0
    if segments is None:
        bold = bool((p.style and p.style.bold) or style.bold)
        segments = para_segments(p, bold, mono, text_spacing(style, p)[1])
    font = style.font
    lines, tail = _lines_tail(segments, width_pt, size_pt, font, 0.0)
    if lines < 2 or tail <= 0 or tail > tk.cjk_orphan_chars + 1e-6:
        return 0.0
    key = (tuple(segments), width_pt, size_pt, font, _default_font, tk.cjk_orphan_chars)
    key += (tk.cjk_squeeze_max, tk.cjk_squeeze_margin)
    hit = _SQUEEZE_CACHE.get(key)
    if hit is None:
        if len(_SQUEEZE_CACHE) > 50_000:
            _SQUEEZE_CACHE.clear()
        hit = 0.0
        narrow = width_pt * (1.0 - tk.cjk_squeeze_margin)
        for k in range(1, int(tk.cjk_squeeze_max / 0.01 + 1e-9) + 1):
            sp = -round(k * 0.01 * size_pt, 2)
            if sp == 0:
                continue
            if _lines_tail(segments, narrow, size_pt, font, sp)[0] < lines:
                hit = sp
                break
        _SQUEEZE_CACHE[key] = hit
    return hit


def paragraphs_height(
    paragraphs: list[Paragraph],
    width_emu: float,
    style: Style,
    scale: float = 1.0,
    *,
    default_size: float = 18,
    mono: bool = False,
    gap: float | None = None,
    squeeze: bool = False,
) -> float:
    """Estimated height in EMU of ``paragraphs`` wrapped into ``width_emu`` (insets already removed).

    ``gap`` is the space before every paragraph but the first, x font size (default: the token).
    ``squeeze`` counts the CJK orphan squeeze (:func:`paragraph_squeeze`) the renderer applies. Off by
    default: the squeeze only removes lines, so the layout stays safe (never too short), and counting it
    inside the growth loops changed text sizes and card heights across decks.
    """
    gap = _tok.para_gap if gap is None else gap
    base = style.font_size or default_size
    font = style.font
    total_pt = 0.0
    for i, p in enumerate(paragraphs):
        size = (p.style.font_size if p.style and p.style.font_size else base) * scale
        indent = list_indent(size, p.level)[0] if p.marker else 0
        wpt = (width_emu - indent) / EMU_PER_PT
        bold = bool((p.style and p.style.bold) or style.bold)
        spc, tf = text_spacing(style, p)
        segs = para_segments(p, bold, mono, tf)
        sq = paragraph_squeeze(p, style, wpt, size, segs, mono=mono) if squeeze else 0.0
        lines = count_lines(segs, wpt, size, font, spc * scale + sq)
        ls = (p.style.line_spacing if p.style and p.style.line_spacing else style.line_spacing) or 1.0
        lh = size * (_tok.line_cjk if has_cjk(p.plain) else _tok.line_latin) * ls
        total_pt += lines * lh + (size * gap if i > 0 else 0)
    return total_pt * EMU_PER_PT * SAFETY


def element_gap(el) -> float | None:
    """The paragraph gap (em) the layout chose for ``el`` (``attrs["para_gap"]``), ``None`` = default."""
    v = getattr(el, "attrs", {}).get("para_gap")
    return float(v) if isinstance(v, (int, float)) else None


def code_height(text: str, width_emu: float, size_pt: float) -> float:
    """Height in EMU of a code block body (monospace, wrapped at the box width)."""
    cols = max(int(width_emu / EMU_PER_PT / (size_pt * 0.6)), 1)
    lines = 0
    for line in text.expandtabs(4).split("\n"):
        lines += max(1, -(-len(line) // cols))
    return lines * size_pt * _tok.line_latin * EMU_PER_PT * SAFETY


def effective_scale(base_size: float, scale: float, min_font: float) -> float:
    """Autofit factor for an element: never shrink below ``min_font`` pt, never grow."""
    if scale >= 1.0 or base_size <= min_font:
        return 1.0
    return min(1.0, max(scale, min_font / base_size))
